### ISSUE TITLE
Segfault when invoking `Login` with undefined `LoginTimeout` field

### ISSUE THREAD

**Issue by andriygm** [peterHoburg/aws-sdk-go-v2-sso-login#35]
`LoginTimeout` should have some default value + there should be some validation to ensure the `AccessToken` field never gets nil dereferenced.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100758574]

goroutine 1 [running]:
github.com/peterHoburg/aws-sdk-go-v2-sso-login.ssoLoginFlow({0x100a3eff8, 0x100f827c0}, 0x14000261040?, 0x1400020b600, 0x0, 0x0)
        /Users/<user>/go/pkg/mod/github.com/peter!hoburg/aws-sdk-go-v2-sso-login@v0.6.2/cred-workflow.go:380 +0x6b4
github.com/peterHoburg/aws-sdk-go-v2-sso-login.Login({0x100a3eff8, 0x100f827c0}, 0x14000055b88)
        /Users/<user>/go/pkg/mod/github.com/peter!hoburg/aws-sdk-go-v2-sso-login@v0.6.2/cred-workflow.go:135 +0x200
```

**Comment by peterHoburg** [comment]
Good catch! I will push a fix tonight. Thanks for opening an issue.

**Comment by peterHoburg** [comment]
v0.6.3 contains the fix
